export const authTypes = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE'
}

export const categoryTypes = {
    GET_CATEGORIES_REQUEST: 'GET_CATEGORIES_REQUEST',
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
    ADD_CATEGORY_REQUEST: 'ADD_CATEGORY_REQUEST',
    ADD_CATEGORY_SUCCESS: 'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAILURE: 'ADD_CATEGORY_FAILURE',
}

export const productTypes = {
    GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
    GET_PRODUCT_BY_SLUG: 'GET_PRODUCT_BY_SLUG',
    GET_PRODUCT_DETAIL_BY_ID_REQUEST: 'GET_PRODUCT_DETAIL_BY_ID_REQUEST',
    GET_PRODUCT_DETAIL_BY_ID_SUCCESS: 'GET_PRODUCT_DETAIL_BY_ID_SUCCESS',
    GET_PRODUCT_DETAIL_BY_ID_FAILURE: 'GET_PRODUCT_DETAIL_BY_ID_FAILURE',
}

export const initialDataTypes = {
    GET_INITIAL_DATAS_REQUEST: 'GET_INITIAL_DATAS_REQUEST',
    GET_INITIAL_DATAS_SUCCESS: 'GET_INITIAL_DATAS_SUCCESS',
    GET_INITIAL_DATAS_FAILURE: 'GET_INITIAL_DATAS_FAILURE'
}

export const pageTypes = {
    CREATE_PAGE_REQUEST: 'CREATE_PAGE_REQUEST',
    CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
    CREATE_PAGE_FAILURE: 'CREATE_PAGE_FAILURE',
    GET_PRODUCT_PAGE_REQUEST: 'GET_PRODUCT_PAGE_REQUEST',
    GET_PRODUCT_PAGE_SUCCESS: 'GET_PRODUCT_PAGE_SUCCESS',
    GET_PRODUCT_PAGE_FAILURE: 'GET_PRODUCT_PAGE_FAILURE'
}